package cn.easyproject.easyee.sm.sys.service;

import java.util.List;

import org.springframework.transaction.annotation.Transactional;

import cn.easyproject.easyee.sm.sys.entity.SysDict;
import cn.easyproject.easyee.sm.base.service.BaseService;

/**
 * SysDict Service, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 *
 */
@Transactional
public interface SysDictService extends BaseService<SysDict> {
	
	/**
	 * Find All
	 * @return list 
	 */
	@Transactional(readOnly = true)
	public SysDict unique(SysDict o);
	
	/**
     * Query list by calatogName
     * @return list 
     */
    @Transactional(readOnly = true)
	public List<SysDict> queryByCname(String catalogName);
}
