package cn.easyproject.easyee.sm.sys.service;

import java.util.List;

import org.springframework.transaction.annotation.Transactional;

import cn.easyproject.easyee.sm.sys.entity.SysDictCatalog;
import cn.easyproject.easyee.sm.base.service.BaseService;

/**
 * SysDictCatalog Service, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 *
 */
@Transactional
public interface SysDictCatalogService extends BaseService<SysDictCatalog> {
	
	/**
     * getNextChild:获取下一级. <br/>  
     *  
     * @author gaojx
     * @param SysDictCatalog o 上级.
     * @return
     */
    @Transactional(readOnly = true)
    public List<SysDictCatalog> getChildNext(SysDictCatalog o);
    
    /**
     * getChildCount:获取下一级数量 <br/>  
     *  
     * @author gaojx  
     * @param SysDictCatalog o 上级.
     * @return
     */
    @Transactional(readOnly = true)
    public int getChildCount(SysDictCatalog o);
}
