package cn.easyproject.easyee.sm.sys.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import cn.easyproject.easyee.sm.sys.entity.SysDictCatalog;
import cn.easyproject.easyee.sm.sys.dao.SysDictCatalogDAO;
import cn.easyproject.easyee.sm.sys.service.SysDictCatalogService;
import cn.easyproject.easyee.sm.base.dao.BaseDAO;
import cn.easyproject.easyee.sm.base.pagination.EasyCriteria;
import cn.easyproject.easyee.sm.base.pagination.PageBean;
import cn.easyproject.easyee.sm.base.service.impl.BaseServiceImpl;

/**
 * SysDictCatalog Service, generated by EasyAuto Must extends BaseService
 * 
 * @author easyproject.cn
 * @version 1.0
 */
@Service("sysDictCatalogService")
public class SysDictCatalogServiceImpl extends BaseServiceImpl<SysDictCatalog> implements SysDictCatalogService {

    @Resource
    private SysDictCatalogDAO sysDictCatalogDAO;

    @Override
    public BaseDAO<SysDictCatalog> getDao() {
        return sysDictCatalogDAO;
    }

    @Override
    public void findByPage(PageBean<SysDictCatalog> pageBean, EasyCriteria sysDictCatalogCriteria) {
        pageBean.setFrom(" SYS_DICT_CATALOG ");
        pageBean.setSelect("*");
        pageBean.setEasyCriteria(sysDictCatalogCriteria);

        // pagination
        sysDictCatalogDAO.pagination(pageBean);
    }

    @Override
    public List<SysDictCatalog> getChildNext(SysDictCatalog o) {
        return sysDictCatalogDAO.getChildNext(o);
    }

    @Override
    public int getChildCount(SysDictCatalog o) {
        return sysDictCatalogDAO.getChildCount(o);
    }
}
