package cn.easyproject.easyee.sm.sys.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import cn.easyproject.easyee.sm.sys.entity.SysDict;
import cn.easyproject.easyee.sm.sys.dao.SysDictDAO;
import cn.easyproject.easyee.sm.sys.service.SysDictService;
import cn.easyproject.easyee.sm.base.dao.BaseDAO;
import cn.easyproject.easyee.sm.base.pagination.EasyCriteria;
import cn.easyproject.easyee.sm.base.pagination.PageBean;
import cn.easyproject.easyee.sm.base.service.impl.BaseServiceImpl;

/**
 * SysDict Service, generated by EasyAuto
 * Must extends BaseService
 * 
 * @author easyproject.cn
 * @version 1.0
 *
 * 
 */
@Service("sysDictService")
public class SysDictServiceImpl extends BaseServiceImpl<SysDict> implements SysDictService {

	@Resource
	private SysDictDAO sysDictDAO;

    @Override
    public BaseDAO<SysDict> getDao() {
        return sysDictDAO;
    }

    @Override
	public void findByPage(PageBean<SysDict> pageBean, EasyCriteria sysDictCriteria) {
		pageBean.setFrom(" SYS_DICT ");
		pageBean.setSelect("*");
		pageBean.setEasyCriteria(sysDictCriteria);
		
		// pagination
		sysDictDAO.pagination(pageBean);
	}

    @Override
    public SysDict unique(SysDict o) {
        return sysDictDAO.unique(o);
    }
    
    @Override
    public List<SysDict> queryByCname(String catalogName) {
        return sysDictDAO.queryByCname(catalogName);
    }

}
