package cn.easyproject.easyee.sm.sys.dao;

import java.util.List;

import cn.easyproject.easyee.sm.base.dao.BaseDAO;
import cn.easyproject.easyee.sm.sys.entity.SysDict;
/**
 * SysDict DAO, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 */
public interface SysDictDAO extends BaseDAO<SysDict> {
	
	/**
     * Unique
     * @param emp Object
     */
    public SysDict unique(SysDict o);
    
    /**
     * Query list by calatogName
     * @param String calatogName
     */
    public List<SysDict> queryByCname(String catalogName);
    
}
