package cn.easyproject.easyee.sm.sys.dao;

import java.util.List;

import cn.easyproject.easyee.sm.base.dao.BaseDAO;
import cn.easyproject.easyee.sm.sys.entity.SysDictCatalog;
/**
 * SysDictCatalog DAO, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 *
 */
public interface SysDictCatalogDAO extends BaseDAO<SysDictCatalog> {
	
	/**
     * getChildNext:获取下级列表<br/>  
     * @author gaojx  
     * @param SysDictCatalog o 上级.
     * @return
     */
    public List<SysDictCatalog> getChildNext(SysDictCatalog o);
    
    /**
     * getChildCount:获取下级数目 <br/>  
     * @author gaojx  
     * @param SysDictCatalog o 上级.
     * @return
     */
    public int getChildCount(SysDictCatalog o);
    
}
