<!--SysDict Edit Page, generated by EasyAuto -->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://www.springframework.org/tags"  prefix="s"%>

<%--  JavaScript  --%>


<script type="text/javascript">
$(function() {
	/*
	 * CRUD
	 */
	//Create or Update
	SysDict.edit = function() {
		var dg=$("#SysDictDataGrid");
		var url = "SysDict/update";
		uiEx.submitURLAjax("#SysDictEditForm", url, function(data) {
			data = eval("(" + data + ")");
			// Refresh datagrid
			if (data.statusCode==200) {
				//uiEx.reloadSelTab("#tabs"); // Refresh Tab
				//dg.datagrid('reload'); //Refresh datagrid, Stay on the current page
				//dg.datagrid('load'); //Refresh datagrid
				dg.datagrid({"pageNumber":data.page});//Refresh datagrid
				uiEx.closeDialog("#SysDictEditDialog");
			} 
		},{"rows":dg.datagrid("options").pageSize});
	}
});

</script>

<%-- 2. Dialog --%>
<div id="SysDictEditDialog" class="easyui-dialog form-layout" style="width:550px;height:auto;" resizable="true" closed="true" buttons="#SysDictEdit-dlg-buttons">
	<div class="ftitle">数据字典<s:message code="label.info"></s:message></div>
	<form id="SysDictEditForm" method="post" >
		<input name="id" type="hidden">
		<table class="table_xz" cellpadding="0" cellspacing="0" width="100%">
			<tr>
    			<td class="td_bg">关键字</td>
    			<td><input class="textbox-gray" name="key" readonly="readonly"></td>
    			<td class="td_bg">字典值</td>
    			<td><input class="easyui-textbox easyui-validatebox" name="value" data-options="required:true,validType:{maxLength:[100]}"></td>
    		</tr>
			<tr>
    			<td class="td_bg">排序号</td>
    			<td><input class="easyui-textbox easyui-numberspinner" name="sortNum" value="1" data-options="min:1,max:100,editable:false"></td>
    			<td class="td_bg">备注</td>
    			<td><input class="easyui-textbox easyui-validatebox" name="remark" data-options="validType:{maxLength:[100]}"></td>
    		</tr>
    	</table>
	</form>
</div>
<div id="SysDictEdit-dlg-buttons">
	<a class="easyui-linkbutton qd" onclick="SysDict.edit()" id="SysDictEditSaveBtn"><s:message code="label.edit"></s:message></a>
	<a class="easyui-linkbutton qd" onclick="javascript:uiEx.closeDialog('#SysDictEditDialog')"><s:message code="label.cancel"></s:message></a>
</div>