<!--SysDict Page, generated by EasyAuto -->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
%>
<%@ taglib uri="http://www.springframework.org/tags"  prefix="s"%>
<%@ taglib uri="http://shiro.apache.org/tags" prefix="shiro"%>

<%--  JavaScript  --%>

<script type="text/javascript">
	// 数据字典 Namespace
	var SysDict = {}, SysDictCatalog = {}, selectedSysDictCatalogNode;	
	$(function() {
		// EasyUI tree root node id
		var rootId = "0";
		// EasyUI tree
		var tt = $('#SysDictCatalogTree').tree({
			data: [{id:rootId,text:'字典分类',state:'closed',iconCls:'icon-tree-group'}],		
			lines: true,
			onBeforeExpand:function(node){
				$(this).tree('options').url = 'SysDictCatalog/getChildTree?parentId=' + node.id;
			},
			onBeforeSelect:function(node){
				if(selectedSysDictCatalogNode && selectedSysDictCatalogNode.id == node.id){
					return false;
				}
				return true;
			},
			onClick: function(node){
				$(this).tree('toggle', node.target);
				if($(this).tree('isLeaf', node.target)){
					$('#SysDictCatalogDeleteBtn').linkbutton('enable');
				} else {
					$('#SysDictCatalogDeleteBtn').linkbutton('disable');
				}
			},
			onSelect:function(node){
				selectedSysDictCatalogNode = node;
				SysDict.doSearch();
			}
		});
		// default open root node
		selectedSysDictCatalogNode = tt.tree('find', rootId);
		tt.tree('expand', selectedSysDictCatalogNode.target);
		
		// EasyUIEx datagrid sort name map
		var fieldSortMap = {};
		fieldSortMap['sortNum'] = 'SORT_NUM';
		// EasyUIEx datagrid
		var dg = $("#SysDictDataGrid").initDatagrid({
			// CRUD URL
			url : "SysDict/list",
			saveUrl : "SysDict/save",
			updateUrl : "SysDict/update",
			destroyUrl : "SysDict/deleteBatch",
			
			idField : "id", // Primary Key Field
			
			showHeaderContextMenu : true, // Datagrid header ContextMenu
			
			pagination : true, // Pagination
			// pageSize: 10,
			// pageList: [10, 20, 30, 40, 50],
			
			//queryParams:{"rows":dg.datagrid("options").pageSize}, // Pagination query parameters
			
			checkbox : true,
			checkOnSelect : true,
			selectOnCheck : false,
			singleSelect : true,
			
			// clickEdit : true, //// Click to edit, EasyUI default is double click
			// autoSave : true, // // Auto save edit
			
			showMsg : true, // The action message is displayed
			
			menuSelector : "#SysDictContextMenu", // ContextMenu
			showContextMenu : false,
			
			sendRowDataPrefix : "", //send parameter name prefix
			
			successKey : "statusCode", //The success key returned by the server
			successValue : "200", //The success value returned by the server
			
			mutipleDelete : true, // Multiple rows are submitted for deletion
			mutipleDeleteProperty : "id", // Multiple rows to mention the attributes and values to the server, will not add sendRowDataPrefix prefix to support the use of an array to specify multiple attribute names
			
			onLoadSuccess : function(data) { },
			
			// on double click
			onDblClickRow : function(rowIndex, rowData) {
				toEdit(rowData);
			},
			onBeforeLoad:function(param){ 
			    var fieldSort = fieldSortMap[param.sort]; 
			    if(fieldSort != '' && fieldSort != undefined){ 
			      //设置新的排序字段名，设置完之后，发送请求时一并会发送到服务端 
			      param.sort = fieldSort; 
			    } 
			} 
		});
		
		/*
		 * Functions
		 */
		// Search
		SysDict.doSearch = function() {
			dg.datagrid("load", {
				'catalogId' : selectedSysDictCatalogNode.id,
				'key' : $("#sysDictKey").val(),
				'value' : $("#sysDictValue").val()
			});
		}

		// Clear all search conditions
		SysDict.clearAll = function() {
			$("#SysDictSearchForm")[0].reset();
			dg.datagrid("load", {'catalogId' : selectedSysDictCatalogNode.id});
		}	
		
		// Destory
		SysDict.toDelete = function() {
			var rows = $("#SysDictDataGrid").datagrid('getChecked');
			if (rows && rows.length > 0) {
				dg.rowDelete(true, false, "statusCode", "200", function(data){}, true);
			} else {
				uiEx.msg("<s:message code="msg.choiceDeleteRow"></s:message>");
			}
		}	
		
		// Add SysDict
		SysDict.toAdd = function() {
			var param = {};
			if(selectedSysDictCatalogNode && selectedSysDictCatalogNode.id != '0'){
				param.catalogId = selectedSysDictCatalogNode.id;
				param.sortNum = dg.datagrid('getRows').length + 1;// 设置默认排序号
				param.remark = selectedSysDictCatalogNode.text;
			} else {
				uiEx.msg("请先选择字典分类");
				return;
			}
			uiEx.resetForm("#SysDictAddForm");
			uiEx.openDialog("#SysDictAddDialog", "数据字典<s:message code="label.add"></s:message>");
			
			uiEx.loadForm("#SysDictAddForm", param, "");
		}	
		
		// Click button to edit
		SysDict.toEdit = function() {
			var row = $("#SysDictDataGrid").datagrid('getSelected');
			if (row) {
				toEdit(row);
			} else {
				uiEx.msg("<s:message code="msg.choiceEditRow"></s:message>");
			}
		}
		
		// Open edit dialog	
		function toEdit(row) {
			uiEx.resetForm("#SysDictEditForm");
			uiEx.openDialog("#SysDictEditDialog", "数据字典<s:message code="label.edit"></s:message>");

			uiEx.loadForm("#SysDictEditForm", row, "");
		}

		// Add SysDictCatalog node
		SysDictCatalog.toAdd = function() {
			var param = {};
			if(selectedSysDictCatalogNode){
				param.parentId = selectedSysDictCatalogNode.id;
				param.parentName = selectedSysDictCatalogNode.text;
				param.sortNum = tt.tree('getChildren',selectedSysDictCatalogNode.target).length + 1;// 设置默认排序号
				param.remark = selectedSysDictCatalogNode.text;
			} else {
				uiEx.msg("请先选择字典分类");
				return;
			}
			uiEx.resetForm("#SysDictCatalogAddForm");
			uiEx.openDialog("#SysDictCatalogAddDialog", "字典分类<s:message code="label.add"></s:message>");
			uiEx.loadForm("#SysDictCatalogAddForm", param, "");
		}
		
		// Edit SysDictCatalog node
		SysDictCatalog.toEdit = function() {
			if (selectedSysDictCatalogNode) {
				if(selectedSysDictCatalogNode.id == '0'){
					uiEx.msg("根节点不允许修改");
					return;
				}
				var param = {};
				param.id = selectedSysDictCatalogNode.id;
				param.parentId = selectedSysDictCatalogNode.parentId;
				param.parentName = tt.tree('getParent',selectedSysDictCatalogNode.target).text;
				param.catalogName = selectedSysDictCatalogNode.text;
				param.sortNum = selectedSysDictCatalogNode.sortNum;
				param.remark = selectedSysDictCatalogNode.remark;
				uiEx.resetForm("#SysDictCataLogEditForm");
				uiEx.openDialog("#SysDictCatalogEditDialog", "字典分类<s:message code="label.edit"></s:message>");
				uiEx.loadForm("#SysDictCatalogEditForm", param, "");
			} else {
				uiEx.msg("请先选择字典分类");
			}
		}
		
		// Destory SysDictCatalog node
		SysDictCatalog.toDelete = function() {
			if (selectedSysDictCatalogNode) {
				if(selectedSysDictCatalogNode.id == '0'){
					uiEx.msg("根节点不允许删除");
					return;
				}
				if(dg.datagrid('getRows').length > 0){
					uiEx.msg("有数据的字典分类不允许删除");
					return;
				}
				uiEx.confirm(uiEx.deleteConfirmMsg, function(res) {
					if(res){
						EasyEE.getJson('SysDictCatalog/delete',{id : selectedSysDictCatalogNode.id},true,function(data){
							if (data['statusCode'] && data['statusCode'] == '200') {
								// refresh root node
								tt.tree('reload',tt.tree('getRoot').target);
								tt.tree('select',tt.tree('getRoot').target);
								uiEx.msg(uiEx.rowDeleteSuccessMsg);
							} else {
								uiEx.msg(uiEx.rowDeleteFailureMsg);
							}
						});
					}
				});
			} else {
				uiEx.msg("<s:message code="msg.choiceDeleteRow"></s:message>");
			}
		}	
	});
</script>

<div class="easyui-layout" style="width:100%;height:100%" >
	<div data-options="region:'west',split:true,title:'字典分类'" style="width:250px;">
		<div class="b_bar_h">
			<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-add',plain:true" onclick="SysDictCatalog.toAdd()" id="SysDictCatalogAddBtn"><s:message code="label.add"></s:message></a>
			<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-edit',plain:true" onclick="SysDictCatalog.toEdit()" id="SysDictCatalogEditBtn"><s:message code="label.edit"></s:message></a>
			<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-remove',plain:true,disabled:true" onclick="SysDictCatalog.toDelete()" id="SysDictCatalogDeleteBtn"><s:message code="label.delete"></s:message></a>
		</div>
		<ul id="SysDictCatalogTree" data-options="animate:true,lines:false"></ul>
	</div>
	<div data-options="region:'center',iconCls:'icon-rights',collapsible:false" >
		<%-- 2. Page  DataGrid --%>
		<table id="SysDictDataGrid" title="数据字典<s:message code="label.list"></s:message>" style="width:100%" toolbar="#SysDictToolbar" idField="id" rownumbers="true" fit="true" fitColumns="true" nowrap="false">
			<thead>
				<tr>
					<th field="ck" checkbox="true" width="50" sortable="true"><s:message code="label.chkbox"></s:message>
					<th field="catalogId" width="50" hidden="true">字典分类</th>
					<th field="key" width="150" halign="center">关键字</th>
					<th field="value" width="150" halign="center">字典值</th>
					<th field="sortNum" width="50" halign="center" sortable="true">排序号</th>
					<th field="remark" width="100" halign="center">备注</th>
				</tr>
			</thead>
		</table>
	</div>
</div>

<%-- 3. ToolBar --%>
<div id="SysDictToolbar">
	<div class="b_line_bar b_bar_h">
		<form action="" id="SysDictSearchForm" onsubmit="SysDict.doSearch();return false">
			<div class="text FL"><span>关键字:</span> <input name="key" id="sysDictKey" class="easyui-textbox" /></div>
			<div class="text FL"><span>字典值:</span> <input name="value" id="sysDictValue" class="easyui-textbox" /></div>
			<div class="bt FL">
				<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-search',plain:true" onclick="SysDict.doSearch()"><s:message code="label.search"></s:message></a>
				<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-clear',plain:true" onclick="SysDict.clearAll()"><s:message code="label.clear"></s:message></a>
			</div>
			<div style="clear:both;"></div>
			<input type="submit" style="display: none;"/>
		</form>
	</div>
	<div class="b_bar_h">
		<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-add',plain:true" onclick="SysDict.toAdd()" id="SysDictAddBtn"><s:message code="label.add"></s:message></a>
		<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-edit',plain:true" onclick="SysDict.toEdit()"><s:message code="label.edit"></s:message></a>
		<a href="javascript:void(0)" class="easyui-linkbutton bt_bg" data-options="iconCls:'icon-remove',plain:true" onclick="SysDict.toDelete()"><s:message code="label.delete"></s:message></a>
	</div>
</div>

<%-- 4. DataGrid ContextMenu --%>
<div id="SysDictContextMenu" class="easyui-menu" style="width:120px;">
	<div onclick="SysDict.toAdd()" data-options="iconCls:'icon-add'"><s:message code="label.add"></s:message></div>
	<div onclick="SysDict.toEdit()" data-options="iconCls:'icon-edit'"><s:message code="label.edit"></s:message></div>
	<div onclick="SysDict.toDelete()" data-options="iconCls:'icon-remove'"><s:message code="label.delete"></s:message></div>
</div>

<%-- 5. Other dialog page --%>
<%@ include file="/WEB-INF/content/dialog/sys/SysDictAdd.jsp"%>
<%@ include file="/WEB-INF/content/dialog/sys/SysDictEdit.jsp"%>
<%@ include file="/WEB-INF/content/dialog/sys/SysDictCatalogAdd.jsp"%>
<%@ include file="/WEB-INF/content/dialog/sys/SysDictCatalogEdit.jsp"%>
