package cn.easyproject.easyee.sm.sys.criteria;

import cn.easyproject.easyee.sm.base.pagination.EasyCriteria;
import cn.easyproject.easyee.sm.base.util.StringUtil;

/**
 * SysDictCatalog Criteria, generated by EasyAuto
 * 
 * @author easyproject.cn
 * @version 1.0
 *
 */
public class SysDictCatalogCriteria extends EasyCriteria implements java.io.Serializable {
    // Fields
    private static final long serialVersionUID = 1L;
    /*
     * 1. Criteria property
     */
    
    private String parentId;

    /*
     * 2. Constructor
     */
    public SysDictCatalogCriteria() {
        super();
    }

    /*
     * 3. 条件生成抽象方法实现
     */
    @Override
    public String getCondition() {
        values.clear(); // 清除条件数据
        StringBuffer condition = new StringBuffer();

        // Your conditions
        /*
        if (StringUtils.isNotNullAndEmpty(this.getName())) {
            condition.append(" and name like #{name}");
            values.put("name", "%" + this.getName() + "%");
        }
        */
        if (StringUtil.isNotNullAndEmpty(this.getParentId())) {
            condition.append(" and PARENT_ID = #{parentId}");
            values.put("parentId", this.getParentId());
        }

        return condition.toString();
    }

    /*
     * 4. Setters & Getters...
     */

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

}