package cn.easyproject.easyee.sm.sys.criteria;

import cn.easyproject.easyee.sm.base.pagination.EasyCriteria;
import cn.easyproject.easyee.sm.base.util.StringUtil;

/**
 * SysDict Criteria, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 *
 */
public class SysDictCriteria extends EasyCriteria implements java.io.Serializable {
	// Fields
	private static final long serialVersionUID = 1L;
	/*
 	 * 1. Criteria property
 	 */
	private String catalogId;
	private String key;
	private String value;
	/*
 	 * 2. Constructor
 	 */
	 public SysDictCriteria() {
		super();
	}

	/*
 	 * 3. 条件生成抽象方法实现
 	 */
	@Override
	public String getCondition() {
		values.clear(); //清除条件数据
		StringBuffer condition = new StringBuffer();
		
		// Your conditions
		
		/*
		if (StringUtils.isNotNullAndEmpty(this.getName())) {
			condition.append(" and name like #{name}");
			values.put("name", "%" + this.getName() + "%");
		}
		*/
		
		if(StringUtil.isNotNullAndEmpty(this.getCatalogId())){
			condition.append(" and CATALOG_ID=#{catalogId}");
			values.put("catalogId", this.getCatalogId());
		}
		if(StringUtil.isNotNullAndEmpty(this.getKey())){
			condition.append(" and key like #{key}");
			values.put("key", "%"+this.getKey()+"%");
		}
		if(StringUtil.isNotNullAndEmpty(this.getValue())){
			condition.append(" and value like #{value}");
			values.put("value", "%"+this.getValue()+"%");
		}
		
		return condition.toString();
	}
	
	 /*
 	 * 4. Setters & Getters...
 	 */ 
  	public String getCatalogId() {
		return catalogId;
	}
	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}
	
  	public String getKey() {
		return key;
	}
	public void setKey(String key) {
		this.key = key;
	}
	
  	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	
}