package ${pkgName}.dao;

import ${pkgName}.entity.${ClassName};

import ${baseDAOImport};

/**
 * ${ClassName} DAO, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 */
public interface ${ClassName}DAO extends BaseDAO<${ClassName}> {
	
}
