package ${pkgName}.service.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import ${pkgName}.dao.${ClassName}DAO;
import ${pkgName}.entity.${ClassName};
import ${pkgName}.service.${ClassName}Service;

import cn.easyproject.easyee.sm.base.dao.BaseDAO;
import cn.easyproject.easyee.sm.base.pagination.EasyCriteria;
import ${pageBeanImport};
import ${baseServiceImplImport};

/**
 * ${ClassName} Service, generated by EasyAuto
 * Must extends BaseService
 * 
 * @author easyproject.cn
 * @version 1.0
 */
@Service("${ClassName?uncap_first}Service")
public class ${ClassName}ServiceImpl extends BaseServiceImpl<${ClassName}> implements ${ClassName}Service {

	@Resource
	private ${ClassName}DAO ${ClassName?uncap_first}DAO;

	@Override
    public BaseDAO<${ClassName}> getDao() {
        return ${ClassName?uncap_first}DAO;
    }
    
	@Override
	public void findByPage(PageBean<${ClassName}> pageBean, EasyCriteria ${ClassName?uncap_first}Criteria) {
		pageBean.setFrom(" ${table} ");
		pageBean.setSelect("*");
		pageBean.setEasyCriteria(${ClassName?uncap_first}Criteria);
		
		// pagination
		${ClassName?uncap_first}DAO.pagination(pageBean);
	}

}
