package ${pkgName}.service;

import org.springframework.transaction.annotation.Transactional;

import ${pkgName}.entity.${ClassName};

import ${baseServiceImport};

/**
 * ${ClassName} Service, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 */
public interface ${ClassName}Service extends BaseService<${ClassName}> {
	
}
